[package]
name = "librarian_search"
version = "0.1.0"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1"
futures = "0.3.15"
js-sys = "0.3.51"
librarian_common = { path = "../librarian_common" }
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
smartstring = "0.2.7"
strsim = "0.10"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.24"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Performance",
    "Request",
    "Response",
    "Window"
]

[profile.release]
lto = true
