[package]
name = "mdbook-morsels"
version = "0.1.0"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.0"
include_dir = "0.6"
mdbook = "0.4"
serde_json = "1.0"
toml = "0.5"
