[package]
name = "mdbook-morsels"
version = "0.0.7"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Morsels plugin for Mdbook."
documentation = "http://ang-zeyu.github.io/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../../README.md"
license = "MIT"
include = ["/src", "/search-ui-dist", "mark.min.js"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.0"
include_dir = "0.7"
mdbook = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
