[package]
name = "librarian_tokenizer"
version = "0.1.0"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4"
regex = "1"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
