[package]
name = "infisearch_common"
version = "0.10.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Internal library for other InfiSearch packages."
documentation = "https://ang-zeyu.github.io/infisearch-website/infisearch/"
repository = "https://github.com/ang-zeyu/infisearch"
readme = "../../README.md"
license = "MIT"

[features]
default = []
indexer = ["serde"]

[dependencies]
byteorder = "1"
serde = { version = "1.0", features = ["derive"], optional = true }
smartstring = "0.2.7"

[dev-dependencies]
pretty_assertions = "0.7.2"
