[workspace]

members = [
    "packages/infisearch",
    "packages/infisearch_common",
    "packages/infisearch_search",
    "packages/mdbook-infisearch",
]

[profile.release]
codegen-units = 1
lto = true
