[package]
name = "morsels_common"
version = "0.3.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Internal library for other morsels packages."
documentation = "https://morsels-search.com/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../../README.md"
license = "MIT"

[features]
default = []
indexer = ["serde"]

[dependencies]
byteorder = "1"
serde = { version = "1.0", features = ["derive"], optional = true }
smartstring = "0.2.7"

[dev-dependencies]
pretty_assertions = "0.7.2"
