[package]
name = "morsels_common"
version = "0.0.3"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Internal library for other morsels packages."
documentation = "http://ang-zeyu.github.io/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../../README.md"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
smartstring = "0.2.7"

[dev-dependencies]
pretty_assertions = "0.7.2"
