[package]
name = "morsels_common"
version = "0.0.0"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
byteorder = "1"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
smartstring = "0.2.7"

[dev-dependencies]
pretty_assertions = "0.7.2"
