[package]
name = "morsels_lang_chinese"
version = "0.3.2"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Chinese tokenizer for morsels."
documentation = "https://morsels-search.com/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../README.md"
license = "MIT"

[features]
indexer = []

[dependencies]
morsels_common = { path = "../../morsels_common", version="=0.3.2" }
morsels_lang_ascii = { path = "../morsels_lang_ascii", version="=0.3.2" }
jieba-rs = { version = "0.6.5", default-features = false, features = [] }
smartstring = "0.2.7"
