[package]
name = "morsels_lang_ascii"
version = "0.0.11"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Basic ascii tokenizer for morsels."
documentation = "http://ang-zeyu.github.io/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../README.md"
license = "MIT"

[features]
indexer = []

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4"
morsels_common = { path = "../../morsels_common", version="0.0.11" }
regex = "1"
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
smartstring = "0.2.7"
