[package]
name = "morsels_lang_ascii"
version = "0.7.0"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Basic ascii tokenizer for morsels."
documentation = "https://morsels-search.com/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../README.md"
license = "MIT"

[features]
indexer = ["lazy_static", "regex"]

[dependencies]
lazy_static = { version = "1.4", optional = true }
morsels_common = { path = "../../morsels_common", version="=0.7.0" }
regex = { version = "1", optional = true }
smartstring = "0.2.7"
