[package]
name = "morsels_indexer"
version = "0.0.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
structopt = "0.3"
crossbeam = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
byteorder = "1"
csv = "1.1"
dashmap = "4"
lazy_static = "1.4"
morsels_common = { path = "../morsels_common" }
morsels_lang_chinese = { path = "../morsels_languages/morsels_lang_chinese" }
morsels_lang_latin = { path = "../morsels_languages/morsels_lang_latin" }
num_cpus = "1.13.0"
path-slash = "0.1.4"
regex = "1"
rustc-hash = "1.1"
scraper = "0.12"
walkdir = "2"