[package]
name = "mdbook-infisearch"
version = "0.10.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "InfiSearch plugin for Mdbook."
documentation = "https://ang-zeyu.github.io/infisearch-website/infisearch/"
repository = "https://github.com/ang-zeyu/infisearch"
readme = "../../README.md"
license = "MIT"
include = ["/src", "mark.min.js", "default_infi_search.json"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.0"
mdbook = "0.4.21"
infisearch = { path = "../infisearch", version="=0.10.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
walkdir = "2"
