[package]
name = "morsels_lang_latin"
version = "0.2.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Ascii tokenizer with stemmers for morsels."
documentation = "https://morsels-search.com/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../README.md"
license = "MIT"

[features]
indexer = []

[dependencies]
morsels_common = { path = "../../morsels_common", version="0.2.1" }
morsels_lang_ascii = { path = "../morsels_lang_ascii", version="0.2.1" }
rust-stemmers = "^1.0"
smartstring = "0.2.7"
