[package]
name = "morsels_lang_latin"
version = "0.0.2"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Ascii tokenizer with stemmers for morsels."
documentation = "http://ang-zeyu.github.io/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../README.md"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4"
morsels_common = { path = "../../morsels_common", version="0.0.2" }
morsels_lang_ascii = { path = "../morsels_lang_ascii", version="0.0.2" }
regex = "1"
rustc-hash = "1.1"
rust-stemmers = "^1.0"
serde = { version = "1.0", features = ["derive"] }
smartstring = "0.2.7"
