[package]
name = "morsels_lang_latin"
version = "0.1.0"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lazy_static = "1.4"
morsels_common = { path = "../../morsels_common" }
regex = "1"
rustc-hash = "1.1"
rust-stemmers = "^1.0"
serde = { version = "1.0", features = ["derive"] }
smartstring = "0.2.7"

[profile.release]
lto = true
