[package]
name = "infisearch"
version = "0.9.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "A complete and more scalable pre-built index approach to client-side search."
documentation = "https://infi-search.com/infisearch/"
repository = "https://github.com/ang-zeyu/infisearch"
readme = "../../README.md"
keywords = ["search"]
categories = ["command-line-utilities"]
license = "MIT"
include = ["/src", "/search-ui-dist"]

[[bin]]
name = "infisearch"
path = "src/main.rs"

[dependencies]
bitvec = "1"
crc32fast = "1.3"
structopt = "0.3"
crossbeam = "0.8"
dircpy = "0.3.13"
include_dir = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
byteorder = "1"
chrono = "0.4.23"
csv = "1.1"
dashmap = "5"
glob = "0.3"
lazy_static = "1.4"
log = { version = "0.4", features = ["max_level_info", "release_max_level_info"] }
log4rs = "1.0"
infisearch_common = { path = "../infisearch_common", version="=0.9.1", features = ["indexer"] }
infisearch_lang_ascii = { path = "../infisearch_languages/infisearch_lang_ascii", version="=0.9.1", features = ["indexer"] }
infisearch_lang_ascii_stemmer = { path = "../infisearch_languages/infisearch_lang_ascii_stemmer", version="=0.9.1", features = ["indexer"] }
infisearch_lang_chinese = { path = "../infisearch_languages/infisearch_lang_chinese", version="=0.9.1", features = ["indexer"] }
num_cpus = "1"
path-absolutize = { version = "3.0", features = ["lazy_static_cache"] }
pathdiff = "0.2"
path-slash = "0.2"
pdf-extract = "0.6"
regex = "1"
rustc-hash = "1.1"
scraper = "0.13"
smartstring = "0.2.7"
walkdir = "2"

[dev-dependencies]
pretty_assertions = "0.7.2"
