[package]
name = "morsels_search"
version = "0.1.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["lang_ascii"]
lang_ascii = ["morsels_lang_ascii"]
lang_latin = ["morsels_lang_latin"]
lang_chinese = ["morsels_lang_chinese"]
perf = []

[dependencies]
byteorder = "1"
futures = "0.3.15"
js-sys = "0.3.51"
miniserde = "0.1"
morsels_common = { path = "../morsels_common", features = [] }
morsels_lang_ascii = { path = "../morsels_languages/morsels_lang_ascii", optional = true, features = [] }
morsels_lang_latin = { path = "../morsels_languages/morsels_lang_latin", optional = true, features = [] }
morsels_lang_chinese = { path = "../morsels_languages/morsels_lang_chinese", optional = true, features = [] }
rustc-hash = "1.1"
smartstring = "0.2.7"
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = "0.4.24"

[dependencies.web-sys]
version = "0.3"
features = [
    "Cache",
    "CacheStorage",
    "console",
    "Performance",
    "Request",
    "Response",
    "Window"
]

[dev-dependencies]
pretty_assertions = "0.7.2"
