[package]
name = "morsels_search"
version = "0.0.11"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["lang_ascii"]
lang_ascii = ["morsels_lang_ascii"]
lang_latin = ["morsels_lang_latin"]
lang_chinese = ["morsels_lang_chinese"]
perf = []

[dependencies]
byteorder = "1"
futures = "0.3.15"
js-sys = "0.3.51"
morsels_common = { path = "../morsels_common" }
morsels_lang_ascii = { path = "../morsels_languages/morsels_lang_ascii", optional = true }
morsels_lang_latin = { path = "../morsels_languages/morsels_lang_latin", optional = true }
morsels_lang_chinese = { path = "../morsels_languages/morsels_lang_chinese", optional = true }
rustc-hash = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
smartstring = "0.2.7"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.24"

[dependencies.web-sys]
version = "0.3"
features = [
    "Cache",
    "CacheStorage",
    "console",
    "Performance",
    "Request",
    "Response",
    "Window"
]

[dev-dependencies]
pretty_assertions = "0.7.2"
