[package]
name = "infisearch_search"
version = "0.8.8"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
default = ["lang_ascii"]
lang_ascii = ["infisearch_lang_ascii"]
lang_latin = ["infisearch_lang_latin"]
lang_chinese = ["infisearch_lang_chinese"]
perf = ["web-sys"]

[dependencies]
byteorder = "1"
js-sys = "0.3.51"
infisearch_common = { path = "../infisearch_common", features = [] }
infisearch_lang_ascii = { path = "../infisearch_languages/infisearch_lang_ascii", optional = true, features = [] }
infisearch_lang_latin = { path = "../infisearch_languages/infisearch_lang_latin", optional = true, features = [] }
infisearch_lang_chinese = { path = "../infisearch_languages/infisearch_lang_chinese", optional = true, features = [] }
smartstring = "0.2.7"
wasm-bindgen = { version = "0.2" }
wasm-bindgen-futures = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Performance",
    "Window"
]
optional = true

# [package.metadata.wasm-pack.profile.release]
# wasm-opt = false

[dev-dependencies]
miniserde = "0.1"
pretty_assertions = "0.7.2"
infisearch_lang_chinese = { path = "../infisearch_languages/infisearch_lang_chinese", features = [] }
