[package]
name = "librarian_indexer"
version = "0.0.1"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
crossbeam = "0.5"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1"
csv = "1.1"
dashmap = "4"
lazy_static = "1.4"
regex = "1"
walkdir = "2"