[book]
authors = ["Ang Ze Yu"]
language = "en"
multilingual = false
src = "src"
title = "InfiSearch Documentation"

[output.html]
default-theme = "infi-theme"
curly-quotes = true
additional-css = ["src/infi-theme.css"]
additional-js = ["src/infi-theme.js"]
git-repository-url = "https://github.com/ang-zeyu/infisearch"
site-url = "/infisearch/"

[output.html.search]
enable = false

[preprocessor.morsels]
command = "mdbook-infisearch"

[output.morsels]
# Note
# "query_param" is documentation specific, for demo-ing the different modes with the buttons
# the only valid modes that should be used are "auto", "dropdown", "fullscreen", "target"
mode = "query_param"
