[book]
authors = ["Ang Ze Yu"]
language = "en"
multilingual = false
src = "src"
title = "Morsels Documentation"

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/ang-zeyu/morsels"
site-url = "/morsels/"

[output.html.search]
enable = false

[preprocessor.morsels]
command = "mdbook-morsels"
renderer = ["html"]

[output.morsels]
portal = true
