[book]
authors = ["Ang Ze Yu"]
language = "en"
multilingual = false
src = "src"
title = "InfiSearch Documentation"

[output.html]
default-theme = "navy"
curly-quotes = true
git-repository-url = "https://github.com/ang-zeyu/infisearch"
site-url = "/infisearch-website/infisearch/"

[output.html.search]
enable = false

[preprocessor.infisearch]
command = "mdbook-infisearch"

[output.infisearch]
# Note
# "query_param" is documentation specific, for demo-ing the different modes with the buttons
# the only valid modes that should be used are "auto", "dropdown", "fullscreen", "target"
mode = "query_param"
