[book]
authors = ["Ze Yu"]
language = "en"
multilingual = false
src = "src"
title = "Morsels Documentation"

[output.html.search]
enable = false

[preprocessor.morsels]
command = "mdbook-morsels"
renderer = ["html"]

[output.morsels]
portal = true
