[book]
authors = ["Ang Ze Yu"]
language = "en"
multilingual = false
src = "src"
title = "Morsels Documentation"

[output.html]
default-theme = "rust"
curly-quotes = true
additional-css = ["src/morsels-theme.css"]
additional-js = ["src/morsels-theme.js"]
git-repository-url = "https://github.com/ang-zeyu/morsels"
site-url = "/morsels/"

[output.html.search]
enable = false

[preprocessor.morsels]
command = "mdbook-morsels"
renderer = ["html"]

[output.morsels]
mode = "target"
