[package]
name = "infisearch_lang_ascii"
version = "0.8.2"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Basic ascii tokenizer for InfiSearch."
documentation = "https://infi-search.com/infisearch/"
repository = "https://github.com/ang-zeyu/infisearch"
readme = "../README.md"
license = "MIT"

[features]
indexer = ["lazy_static", "regex"]

[dependencies]
lazy_static = { version = "1.4", optional = true }
infisearch_common = { path = "../../infisearch_common", version="=0.8.2" }
regex = { version = "1", optional = true }
smartstring = "0.2.7"
