name: Build Binaries
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build-binaries:
    name: Build ${{ matrix.os }} Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-22
          default: true
          override: true
          target: ${{ matrix.target }}
          components: rust-src
      - uses: Swatinem/rust-cache@v1
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm i -g npm
      - run: npm run setup
      - run: npm run buildSearch

      - name: Build indexer x86_64
        run: cargo build --release --target ${{ matrix.target }} -p morsels_indexer
      - name: Build mdbook plugin x86_64
        run: cargo build --release --target ${{ matrix.target }} -p mdbook-morsels
      - name: Zip binaries
        run: zip -j target/indexer.${{ matrix.target }}.zip target/${{ matrix.target }}/release/morsels target/${{ matrix.target }}/release/mdbook-morsels
        if: matrix.os != 'windows-latest'
      - name: Zip binaries
        run: tar -c -f target/indexer.${{ matrix.target }}.zip --directory=target/${{ matrix.target }}/release morsels.exe mdbook-morsels.exe
        if: matrix.os == 'windows-latest'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/indexer.*.zip
          file_glob: True
          tag: ${{ github.ref }}

      - name: Zip Search Package
        run: zip -j search.morsels.zip packages/search-ui/dist/*
        if: matrix.os == 'ubuntu-latest'

      - name: Upload search package to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: search.morsels.zip
          asset_name: search.morsels.zip
          tag: ${{ github.ref }}
        if: matrix.os == 'ubuntu-latest'
