name: Build Binaries
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build-binaries:
    name: Build ${{ matrix.os }} Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extra_target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            extra_target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
            extra_target: aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-22
          default: true
          override: true
          target: ${{ matrix.extra_target }}
          components: rust-src
      - uses: Swatinem/rust-cache@v1

      - name: Build indexer x86_64
        run: cargo build --release --target ${{ matrix.target }} -p morsels_indexer
      - name: Build mdbook plugin x86_64
        run: cargo build --release --target ${{ matrix.target }} -p mdbook-morsels
      - name: Zip binaries
        run: zip -j target/indexer.${{ matrix.target }}.zip target/${{ matrix.target }}/release/morsels target/${{ matrix.target }}/release/mdbook-morsels
        if: matrix.os != 'windows-latest'
      - name: Zip binaries
        run: tar -c -f target/indexer.${{ matrix.target }}.zip --directory=target/${{ matrix.target }}/release morsels.exe mdbook-morsels.exe
        if: matrix.os == 'windows-latest'

      - name: Build indexer aarch-64
        run: cargo build --release --target ${{ matrix.extra_target }} -p morsels_indexer
        if: matrix.os == 'macos-latest'
      - name: Build mdbook plugin aarch-64
        run: cargo build --release --target ${{ matrix.extra_target }} -p mdbook-morsels
        if: matrix.os == 'macos-latest'
      - name: Zip binaries
        run: zip -j target/indexer.${{ matrix.extra_target }}.zip target/${{ matrix.extra_target }}/release/morsels target/${{ matrix.extra_target }}/release/mdbook-morsels
        if: matrix.os == 'macos-latest'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/indexer.*.zip
          file_glob: True
          tag: ${{ github.ref }}

      - name: Zip Search Package
        run: zip -j search.morsels.zip packages/search-ui/dist/*
        if: matrix.os == 'ubuntu-latest'

      - name: Upload search package to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: search.morsels.zip
          asset_name: search.morsels.zip
          tag: ${{ github.ref }}
        if: matrix.os == 'ubuntu-latest'
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: cargo install mdbook
      - run: cargo install mdbook-morsels
      - run: npm run buildDocs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: docs/book/html
          repository-name: ang-zeyu/morsels-website
          target-folder: morsels
          ssh-key: ${{ secrets.DOCS }}
