name: Build Binaries
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build-binaries:
    name: Build ${{ matrix.os }} Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target_1: x86_64-unknown-linux-gnu
          - os: windows-latest
            target_1: x86_64-pc-windows-msvc
          - os: macos-latest
            target_1: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.os == 'macos-latest' && 'aarch64-apple-darwin' || null }}
      - uses: Swatinem/rust-cache@v1

      - name: Build indexer x86_64
        run: cargo build --release --target ${{ matrix.target_1 }} -p morsels_indexer
      - name: Build mdbook plugin x86_64
        run: cargo build --release --target ${{ matrix.target_1 }} -p mdbook-morsels
      - name: Zip binaries
        run: zip -j target/indexer.${{ matrix.target_1 }}.zip target/${{ matrix.target_1 }}/release/morsels target/${{ matrix.target_1 }}/release/mdbook-morsels
        if: matrix.os != 'windows-latest'
      - name: Zip binaries
        run: tar -c -f target/indexer.${{ matrix.target_1 }}.zip --directory=target/${{ matrix.target_1 }}/release morsels.exe mdbook-morsels.exe
        if: matrix.os == 'windows-latest'

      - name: Build indexer aarch64
        run: cargo build --release --target aarch64-apple-darwin -p morsels_indexer
        if: matrix.os == 'macos-latest'
      - name: Build mdbook plugin aarch64
        run: cargo build --release --target aarch64-apple-darwin -p mdbook-morsels
        if: matrix.os == 'macos-latest'
      - name: Zip binaries
        run: zip -j target/indexer.aarch64-apple-darwin.zip target/aarch64-apple-darwin/release/morsels target/aarch64-apple-darwin/release/mdbook-morsels
        if: matrix.os == 'macos-latest'

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/indexer.*.zip
          file_glob: True
          tag: ${{ github.ref }}

      - name: Zip Search Package
        run: zip -j search.morsels.zip packages/search-ui/dist/*
        if: matrix.os == 'ubuntu-latest'

      - name: Upload search package to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: search.morsels.zip
          asset_name: search-bundle
          tag: ${{ github.ref }}
        if: matrix.os == 'ubuntu-latest'
