name: ci
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-22
          default: true
          override: true
          target: ${{ matrix.target }}
          components: rust-src
      - uses: Swatinem/rust-cache@v1
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm i -g npm
      - run: npm run setup
      - run: npm run test
  build-docs:
    needs: ci
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v1
      - run: cargo install mdbook
      - run: cargo install mdbook-morsels
      - run: npm run buildDocs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: docs/book/html
          repository-name: ang-zeyu/morsels-website
          target-folder: morsels
          ssh-key: ${{ secrets.DOCS }}
