name: ci
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm i -g npm
      - run: npm run setup
      - run: npm run test
  build-docs:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm i -g npm
      - run: npm run setup
      - run: cargo install mdbook
      - run: cargo clean --release -p morsels_indexer
      - run: npm run installIndexer
      - run: npm run buildSearch
      - run: cargo clean --release -p mdbook-morsels
      - run: npm run installMdbook
      - run: npm run buildDocs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: docs/book/html
          repository-name: ang-zeyu/morsels-demo-1
          target-folder: morsels
          token: docs
