[package]
name = "infisearch_lang_chinese"
version = "0.9.0"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Chinese tokenizer for InfiSearch."
documentation = "https://infi-search.com/infisearch/"
repository = "https://github.com/ang-zeyu/infisearch"
readme = "../README.md"
license = "MIT"

[features]
indexer = ["regex"]

[dependencies]
infisearch_common = { path = "../../infisearch_common", version="=0.9.0" }
infisearch_lang_ascii = { path = "../infisearch_lang_ascii", version="=0.9.0" }
lazy_static = { version = "1.4" }
regex = { version = "1", optional = true }
smartstring = "0.2.7"
