[package]
name = "infisearch_lang_chinese"
version = "0.7.3"
authors = ["Ze Yu <angzeyu@gmail.com>"]
edition = "2018"
description = "Chinese tokenizer for morsels."
documentation = "https://morsels-search.com/morsels/"
repository = "https://github.com/ang-zeyu/morsels"
readme = "../README.md"
license = "MIT"

[features]
indexer = ["regex"]

[dependencies]
infisearch_common = { path = "../../infisearch_common", version="=0.7.3" }
infisearch_lang_ascii = { path = "../infisearch_lang_ascii", version="=0.7.3" }
lazy_static = { version = "1.4" }
regex = { version = "1", optional = true }
smartstring = "0.2.7"
